param(
    [string]$ProjectName
)

$ErrorActionPreference = 'Stop'

function Write-Utf8NoBomText {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [AllowEmptyString()]
        [Parameter(Mandatory = $true)]
        [string]$Content
    )

    $directory = Split-Path -Parent $Path
    if ($directory -and -not (Test-Path -LiteralPath $directory)) {
        New-Item -ItemType Directory -Path $directory -Force | Out-Null
    }

    $encoding = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $encoding)
}

function New-SecretKey {
    # Django usa una clave aleatoria de 50 caracteres con este alfabeto.
    $chars = 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)'
    $bytes = New-Object byte[] 50
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $builder = New-Object System.Text.StringBuilder
    foreach ($byte in $bytes) {
        [void]$builder.Append($chars[$byte % $chars.Length])
    }
    $builder.ToString()
}

function Normalize-ProjectName {
    param([string]$Name)

    $normalized = $Name.Trim()
    if ([string]::IsNullOrWhiteSpace($normalized)) { throw 'Debes indicar un nombre de proyecto valido.' }
    if ($normalized -notmatch '^[A-Za-z_][A-Za-z0-9_]*$') { throw 'El nombre debe ser un identificador Python valido: solo letras, numeros y guion bajo.' }
    return $normalized
}

function Get-PythonCommand {
    $python = Get-Command python -ErrorAction SilentlyContinue
    if ($python) { return $python.Source }
    $py = Get-Command py -ErrorAction SilentlyContinue
    if ($py) { return $py.Source }
    return $null
}

if ([string]::IsNullOrWhiteSpace($ProjectName)) {
    $ProjectName = Read-Host 'Nombre del proyecto'
}

$ProjectName = Normalize-ProjectName -Name $ProjectName
$sourceRoot = 'D:\Proyectos GIT\reserva'
$destinationPath = Join-Path (Get-Location).Path $ProjectName
if (Test-Path -LiteralPath $destinationPath) { throw "La carpeta destino ya existe: $destinationPath" }
New-Item -ItemType Directory -Path $destinationPath -Force | Out-Null

foreach ($dir in @('applications\home\migrations','applications\users\migrations','templates')) {
    New-Item -ItemType Directory -Path (Join-Path $destinationPath $dir) -Force | Out-Null
}

New-Item -ItemType Directory -Path (Join-Path $destinationPath 'media') -Force | Out-Null

$files = @{}
$files['applications\home\migrations\__init__.py'] = ""
$files['applications\users\migrations\__init__.py'] = ""
$files['.gitignore'] = @"
venv/
env/
__pycache__/
*.pyc
*.pyo
db.sqlite3
media/
staticfiles/
.env
.vscode/
.idea/
*.log
"@

$files['requirements.txt'] = @"
Django==3.2.25
asgiref==3.11.1
sqlparse==0.4.4
pytz==2024.1
django-environ==0.11.2
Pillow==9.5.0
django-model-utils==5.0.0
psycopg2-binary==2.9.9
"@

$files['manage.py'] = @"
#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys

def main():
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', '$ProjectName.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)

if __name__ == '__main__':
    main()
"@

$files["$ProjectName\__init__.py"] = ""
$files["$ProjectName\asgi.py"] = @"
import os
from django.core.asgi import get_asgi_application
os.environ.setdefault('DJANGO_SETTINGS_MODULE', '$ProjectName.settings')
application = get_asgi_application()
"@
$files["$ProjectName\wsgi.py"] = @"
import os
from django.core.wsgi import get_wsgi_application
os.environ.setdefault('DJANGO_SETTINGS_MODULE', '$ProjectName.settings')
application = get_wsgi_application()
"@
$files["$ProjectName\settings.py"] = @"
"""
Django settings for $ProjectName project.

Generated by 'django-admin startproject' using Django 3.2.25.
"""

from pathlib import Path
import environ

# --------------------------------------------------
# BASE DIR
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------------
# django-environ
# --------------------------------------------------
env = environ.Env(
    DEBUG=(bool, False)
)

# Leer archivo .env
environ.Env.read_env(BASE_DIR / '.env')

# --------------------------------------------------
# SECURITY
# --------------------------------------------------
SECRET_KEY = env('SECRET_KEY')

DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

# --------------------------------------------------
# APPLICATIONS
# --------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'applications.users',
    'applications.home',
]

# --------------------------------------------------
# MIDDLEWARE
# --------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --------------------------------------------------
# URLS
# --------------------------------------------------
ROOT_URLCONF = '$ProjectName.urls'

# --------------------------------------------------
# TEMPLATES
# --------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Procesadores personalizados
                # 'applications.procesors.home_contact',
            ],
        },
    },
]

# --------------------------------------------------
# WSGI
# --------------------------------------------------
WSGI_APPLICATION = '$ProjectName.wsgi.application'

# --------------------------------------------------
# DATABASE
# --------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='5432'),
    }
}

# --------------------------------------------------
# PASSWORD VALIDATION
# --------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --------------------------------------------------
# INTERNATIONALIZATION
# --------------------------------------------------
LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# --------------------------------------------------
# STATIC FILES
# --------------------------------------------------
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

FIXTURE_DIRS = [
    BASE_DIR / 'fixtures'
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# --------------------------------------------------
# MEDIA FILES
# --------------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --------------------------------------------------
# DEFAULT PRIMARY KEY
# --------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

LOGIN_URL = 'app_users:login'
LOGIN_REDIRECT_URL = 'app_users:dashboard'
LOGOUT_REDIRECT_URL = 'app_users:login'
"@
$files["$ProjectName\urls.py"] = @"
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('users/', include('applications.users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"@

$files['.env'] = @"
# -------------------------
# Django
# -------------------------
SECRET_KEY=$(New-SecretKey)
DEBUG=True
ALLOWED_HOSTS=localhost,127.0.0.1

# -------------------------
# Database
# -------------------------
DB_NAME=db_reserva2026
DB_USER=russell
DB_PASSWORD=russell2020
DB_HOST=localhost
DB_PORT=5432
"@
$files['activar.bat'] = "@echo off`r`ncd /d ""%~dp0""`r`ncall venv\Scripts\activate`r`ncmd /k`r`n"
$files['README.md'] = "# $ProjectName`r`n"
$files['applications\__init__.py'] = ""
$files['applications\home\__init__.py'] = ""
$files['applications\users\__init__.py'] = ""
$files['applications\home\admin.py'] = @"
from django.contrib import admin

# Register your models here.
"@
$files['applications\home\apps.py'] = @"
from django.apps import AppConfig

class HomeConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'applications.home'
"@
$files['applications\home\models.py'] = @"
from django.db import models

# Create your models here.
"@
$files['applications\home\tests.py'] = @"
from django.test import TestCase

# Create your tests here.
"@
$files['applications\home\urls.py'] = @"
from django.urls import path
from . import views

app_name = 'app_home'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]
"@
$files['applications\home\views.py'] = @"
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'home/index.html'
"@
$files['applications\users\admin.py'] = @"
from django.contrib import admin

from .models import User

admin.site.register(User)
"@
$files['applications\users\apps.py'] = @"
from django.apps import AppConfig

class UsersConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'applications.users'
"@
$files['applications\users\forms.py'] = @"
from django import forms
from .models import User


class UserRegisterForm(forms.Form):
    email = forms.EmailField(label='Correo electrónico')
    first_name = forms.CharField(label='Nombres', max_length=50)
    last_name = forms.CharField(label='Apellidos', max_length=50)
    occupation = forms.ChoiceField(label='Ocupación', choices=User.OCCUPATION_CHOICES)
    gender = forms.ChoiceField(label='Género', choices=User.GENDER_CHOICES)
    phone = forms.CharField(label='Celular', max_length=15, required=False)
    date_birth = forms.DateField(label='Fecha de nacimiento', required=False)
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmar contraseña', widget=forms.PasswordInput)


class LoginForm(forms.Form):
    email = forms.EmailField(label='Correo electrónico')
    password = forms.CharField(label='Contraseña', widget=forms.PasswordInput)


class UpdatePasswordForm(forms.Form):
    password1 = forms.CharField(label='Contraseña actual', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Nueva contraseña', widget=forms.PasswordInput)
"@
$files['applications\users\managers.py'] = @"
from django.contrib.auth.models import BaseUserManager


class UserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_active', True)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        return self._create_user(email, password, **extra_fields)
"@
$files['applications\users\mixins.py'] = @"
from django.contrib.auth.mixins import LoginRequiredMixin


class AdministradorPermisoMixin(LoginRequiredMixin):
    pass
"@
$files['applications\users\models.py'] = @"
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    ADMINISTRADOR = '0'
    PACIENTE = '1'
    RECEPCION = '2'
    DOCTOR = '3'

    VARON = 'M'
    MUJER = 'F'
    OTRO = 'O'

    OCCUPATION_CHOICES = (
        (ADMINISTRADOR, 'Administrador'),
        (PACIENTE, 'Paciente'),
        (RECEPCION, 'Recepcion'),
        (DOCTOR, 'Doctor'),
    )

    GENDER_CHOICES = (
        (VARON, 'Masculino'),
        (MUJER, 'Femenino'),
        (OTRO, 'Otro'),
    )

    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    occupation = models.CharField(max_length=3, choices=OCCUPATION_CHOICES, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    date_birth = models.DateField(null=True, blank=True)
    phone = models.CharField(max_length=15, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']
"@
$files['applications\users\services.py'] = ""
$files['applications\users\tests.py'] = ""
$files['applications\users\urls.py'] = @"
from django.urls import path
from . import views

app_name = 'app_users'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('update/', views.UpdatePasswordView.as_view(), name='user-update'),
    path('', views.DashboardView.as_view(), name='dashboard'),
]
"@
$files['applications\users\views.py'] = @"
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import View
from django.views.generic.edit import FormView

from .forms import LoginForm, UpdatePasswordForm, UserRegisterForm
from .models import User


class UserRegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('app_users:login')

    def form_valid(self, form):
        User.objects.create_user(
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            first_name=form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name'],
            occupation=form.cleaned_data['occupation'],
            gender=form.cleaned_data['gender'],
            date_birth=form.cleaned_data['date_birth'],
            phone=form.cleaned_data.get('phone', ''),
        )
        return super().form_valid(form)


class LoginUser(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('app_users:dashboard')

    def form_valid(self, form):
        user = authenticate(
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password']
        )
        if user is None:
            form.add_error(None, 'Email o contraseña incorrectos.')
            return self.form_invalid(form)
        login(self.request, user)
        return super().form_valid(form)


class LogoutView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(reverse('app_users:login'))


class UpdatePasswordView(LoginRequiredMixin, FormView):
    template_name = 'users/cambiar_password.html'
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('app_users:login')
    login_url = reverse_lazy('app_users:login')

    def form_valid(self, form):
        usuario = self.request.user
        user = authenticate(
            email=usuario.email,
            password=form.cleaned_data['password1']
        )
        if user is None:
            form.add_error(None, 'La contraseña actual es incorrecta.')
            return self.form_invalid(form)

        usuario.set_password(form.cleaned_data['password2'])
        usuario.save()
        logout(self.request)
        return super().form_valid(form)


class DashboardView(LoginRequiredMixin, View):
    template_name = 'users/dashboard.html'
    login_url = reverse_lazy('app_users:login')

    def get(self, request):
        return render(request, self.template_name, {'user': request.user})
"@
foreach ($path in $files.Keys) {
    Write-Utf8NoBomText -Path (Join-Path $destinationPath $path) -Content $files[$path]
}

$pythonCmd = Get-PythonCommand
if ($pythonCmd) {
    $venvPath = Join-Path $destinationPath 'venv'
    $venvPython = Join-Path $venvPath 'Scripts\python.exe'
    & $pythonCmd -m venv $venvPath
    if ($LASTEXITCODE -ne 0) { throw 'No se pudo crear el entorno virtual.' }
    & $venvPython -m pip install --upgrade pip
    if ($LASTEXITCODE -ne 0) { throw 'No se pudo actualizar pip.' }
    & $venvPython -m pip install -r (Join-Path $destinationPath 'requirements.txt')
    if ($LASTEXITCODE -ne 0) { throw 'No se pudieron instalar las dependencias.' }
}

Write-Host "Proyecto creado correctamente en: $destinationPath"
